CFLAGS  = -Wall -Wextra -pedantic -std=c99
# LDFLAGS = -L/usr/local/lib
# LDLIBS  = -lm -lSDL2

sources = src/main.cpp src/chip8.cpp
headers = src/inc/chip8.h

all: bin/emulator.out

bin/emulator.out: $(sources) $(headers)
        @mkdir -p bin
        $(CC) $(CFLAGS) $(LDFLAGS) -o $@ $(sources) $(LDLIBS)

clean:
        rm -rf bin